server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /user-service/h2-console
      settings:
        web-allow-others: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce Application

token:
  expiration_time: ${TOKEN_EXPIRATION_TIME:86400000}
  secret: ${TOKEN_SECRET:secret}
